name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run dotnet restore
        run: dotnet restore SalesWebMvc/SalesWebMvc.sln

      - name: Run dotnet build
        run: dotnet build SalesWebMvc/SalesWebMvc.sln

  tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3

      - name: Run unit tests
        run: dotnet test --no-restore --verbosity normal SalesWebMvc/SalesWebMvc.sln